### ISSUE TITLE
Bug: Fix "bytecode doesn't match..." error when verifying contracts

### ISSUE THREAD

**Issue by kamescg** [pooltogether/v4-mainnet#15]
Several contracts have to manually verified after deploying to Optimism:

- PrizeDistributionFactory
- PrizeFlush
- PrizeTierHistory
- TwabRewards

The error might be caused by different compiler settings between `v4-mainnet` and `v4-core`.

The compiler/optimizer is generating non-matching bytecode, which is why I believe the compile process is probably the source of the verification problems.

**Comment by PierrickGT** [comment]
This problem hasn't occur during recent Optimism deployments. Closing for now.
